import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("builds the static Huzzle application shell", async () => {
  const html = await readFile(new URL("../dist/index.html", import.meta.url), "utf8");
  assert.match(html, /<title>Huzzle<\/title>/i);
  assert.match(html, /<div id="root"><\/div>/);
  assert.match(html, /type="module"/);
});

test("keeps the core PIXI puzzle mechanics configured", async () => {
  const source = await readFile(new URL("../app/pixi-puzzle.ts", import.meta.url), "utf8");
  assert.match(source, /export type GridSize = 4 \| 6 \| 8/);
  assert.match(source, /export type TileShape = "square" \| "hexagon" \| "octagon"/);
  assert.match(source, /const TILE_GAP = 0/);
  assert.match(source, /const TILE_TEXTURE_SIZE = 256/);
  assert.match(source, /normalizeImage/);
  assert.match(source, /gridSize \* TILE_TEXTURE_SIZE/);
  assert.match(source, /sprite\.roundPixels = true/);
  assert.doesNotMatch(source, /const shadow = new Graphics/);
  assert.match(source, /relocateGroup/);
  assert.match(source, /recomputeConnections/);
  assert.match(source, /connectedNeighbors/);
  assert.match(source, /drawComponentOutline/);
  assert.match(source, /color: 0xffffff, width: 3/);
  assert.doesNotMatch(source, /outline\.roundRect/);
  assert.match(source, /activeGroup\.forEach/);
  assert.match(source, /pointerdown/);
  assert.match(source, /pointermove/);
  assert.match(source, /tile\.slot === tile\.row \* gridSize \+ tile\.col/);
  assert.match(source, /coordinateFor/);
  assert.match(source, /coordinateDistance/);
  assert.match(source, /new Polygon\(tilePoints\)/);
  assert.match(source, /new Graphics\(\)\.poly\(tilePoints\)\.fill/);
  assert.match(source, /tileShape === "hexagon"/);
  assert.match(source, /const hexImageSize = Math\.max\(gridWidth, gridHeight\)/);
  assert.match(source, /sprite\.width = hexImageSize/);
  assert.match(source, /sprite\.height = hexImageSize/);
  assert.match(source, /const octagonCut = tileWidth \* \(1 - Math\.SQRT1_2\)/);
  assert.match(source, /tileShape === "octagon"/);
  assert.match(source, /tileShape !== "square"/);
  assert.match(source, /minimumSwapsToSolve/);
  assert.match(source, /onStart\(\)/);
  assert.match(source, /Math\.max\(4, Math\.ceil\(requiredMoves \* \.5\)\)/);

  const studio = await readFile(new URL("../app/puzzle-studio.ts", import.meta.url), "utf8");
  assert.match(studio, /const GRID_OPTIONS: GridSize\[\] = \[4, 6, 8\]/);
  assert.match(studio, /gridSize: this\.gridSize/);
  assert.match(studio, /changeGridSize/);
  assert.match(studio, /const SHAPE_OPTIONS/);
  assert.match(studio, /\{ value: "octagon", label: "Octagon" \}/);
  assert.match(studio, /changeTileShape/);
  assert.match(studio, /tileShape: this\.tileShape/);
  assert.match(studio, /20 \+ this\.progress\.startingGroups \* 7/);
  assert.match(studio, /this\.progress\.moves > this\.progress\.moveLimit/);
  assert.match(studio, /this\.progress\.moveLimit \|\| "—"/);
  assert.match(studio, /this\.gameStarted \|\| this\.progress\.won/);
  assert.match(studio, /this\.targetRevealed \|\| this\.progress\.won/);
  assert.match(studio, /stars === 3 \? "Excellent!" : stars === 2 \? "Well done!" : "Puzzle completed!"/);
  assert.doesNotMatch(studio, /Picture complete!/);
  assert.match(studio, /Reveal target image for a one-star penalty/);
  assert.match(studio, /<small aria-hidden="true">−★<\/small>/);
  assert.match(studio, /\$\{stars\} of 3 stars remaining/);
  assert.doesNotMatch(studio, /<span>Sets<\/span>/);
  assert.doesNotMatch(studio, /<span>Grid<\/span>/);
  assert.match(studio, /<legend>Piece shape<\/legend>/);
  assert.ok(studio.indexOf('class="shape-picker"') < studio.indexOf('class="grid-picker"'));
  assert.match(studio, /huzzle-theme/);
  assert.match(studio, /Switch to \$\{this\.theme === "light" \? "dark" : "light"\} mode/);
  assert.match(studio, /soundManager\.playSound\(SOUNDTRACK, true\)/);
  assert.match(studio, /Mute soundtrack/);

  const soundManager = await readFile(new URL("../app/sound-manager.ts", import.meta.url), "utf8");
  assert.match(soundManager, /playSound\(sound: string, loop = false\)/);
  assert.match(soundManager, /stopSound\(sound\?: string\)/);

  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  assert.match(styles, /:root\[data-theme="dark"\]/);
  assert.match(styles, /\.theme-toggle/);

  assert.doesNotMatch(studio, /picture puzzle lab/);
  assert.doesNotMatch(studio, /Build the whole picture/);
  assert.doesNotMatch(studio, /Mechanic prototype/);
  assert.doesNotMatch(studio, /PIXI\.js interaction prototype/);
  assert.doesNotMatch(studio, /landscapes and square images work best/);
  assert.doesNotMatch(studio, /Correct neighbors connect into movable sets/);
  assert.doesNotMatch(studio, /Shuffle and restart puzzle/);
  assert.doesNotMatch(studio, /Swap tiles\. Build connected sets/);
  assert.doesNotMatch(studio, /Every tile stays inside the square playfield/);
  assert.doesNotMatch(studio, /Drag a tile/);
  assert.doesNotMatch(studio, /Release and displaced tiles/);
  assert.doesNotMatch(studio, /The outer outline shows exactly what moves together/);
  assert.doesNotMatch(studio, /Choose another image/);
  assert.match(studio, />Upload image<input/);
  assert.ok(studio.indexOf("Upload image") < studio.indexOf('class="grid-picker"'));

  const main = await readFile(new URL("../app/main.ts", import.meta.url), "utf8");
  assert.match(main, /mountPuzzleStudio\(root\)/);
  assert.doesNotMatch(main + studio + source, /from "react"|react-dom|createRoot|useEffect|useState|useRef/);
});
