import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("builds the static Huzzle application shell", async () => {
  const html = await readFile(new URL("../dist/index.html", import.meta.url), "utf8");
  assert.match(html, /<title>Huzzle<\/title>/i);
  assert.match(html, /<div id="root"><\/div>/);
  assert.match(html, /type="module"/);
});

test("keeps the configured PIXI puzzle mechanics", async () => {
  const scene = await readFile(new URL("../app/scenes/puzzleScene.ts", import.meta.url), "utf8");
  const board = await readFile(new URL("../app/components/puzzle/puzzleBoard.ts", import.meta.url), "utf8");
  const hud = await readFile(new URL("../app/components/puzzle/puzzleHUD.ts", import.meta.url), "utf8");
  const controls = await readFile(new URL("../app/components/puzzle/puzzleControls.ts", import.meta.url), "utf8");
  const preview = await readFile(new URL("../app/components/puzzle/targetPreview.ts", import.meta.url), "utf8");
  const completion = await readFile(new URL("../app/components/puzzle/completionModal.ts", import.meta.url), "utf8");
  const header = await readFile(new URL("../app/components/appHeader.ts", import.meta.url), "utf8");
  const gameConfig = await readFile(new URL("../app/config/gameConfig.ts", import.meta.url), "utf8");
  const appConfig = await readFile(new URL("../app/config/appConfig.ts", import.meta.url), "utf8");
  const sceneConfig = await readFile(new URL("../app/config/scenes/puzzleSceneConfig.ts", import.meta.url), "utf8");
  const customLevelConfig = await readFile(new URL("../app/config/scenes/customLevelSceneConfig.ts", import.meta.url), "utf8");
  const types = await readFile(new URL("../app/types/gameTypes.ts", import.meta.url), "utf8");
  const images = await readFile(new URL("../app/systems/imageProcessor.ts", import.meta.url), "utf8");
  const soundManager = await readFile(new URL("../app/systems/soundManager.ts", import.meta.url), "utf8");
  const themeManager = await readFile(new URL("../app/systems/themeManager.ts", import.meta.url), "utf8");
  const sceneManager = await readFile(new URL("../app/systems/sceneManager.ts", import.meta.url), "utf8");
  const introScene = await readFile(new URL("../app/scenes/gameIntroScene.ts", import.meta.url), "utf8");
  const mainMenuScene = await readFile(new URL("../app/scenes/mainMenuScene.ts", import.meta.url), "utf8");
  const main = await readFile(new URL("../app/index.ts", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");

  assert.match(types, /export type GridSize = 4 \| 6 \| 8/);
  assert.match(types, /export type TileShape = "square" \| "hexagon" \| "octagon"/);
  assert.match(gameConfig, /defaultSize: 4 as GridSize/);
  assert.match(gameConfig, /sizes: \[4, 6, 8\]/);
  assert.match(gameConfig, /\{ value: "octagon", label: "Octagon" \}/);
  assert.match(gameConfig, /secondsPerStartingSet: 7/);
  assert.match(gameConfig, /moveAllowanceMultiplier: \.5/);
  assert.match(gameConfig, /minimumFreeMoves: 4/);
  assert.match(appConfig, /file: "sounds\/huzzle-soundtrack\.wav"/);
  assert.match(appConfig, /durationMs: 1800/);
  assert.match(appConfig, /storageKey: "huzzle-sfx-muted"/);
  assert.match(appConfig, /resolveAssetPath/);
  assert.match(sceneConfig, /showMoves: true/);
  assert.match(sceneConfig, /allowImageUpload: true/);
  assert.match(sceneConfig, /completionModal/);
  assert.match(customLevelConfig, /export const customLevelSceneConfig/);
  assert.match(customLevelConfig, /controls: \{\s+enabled: true/);

  assert.match(images, /createSampleImage/);
  assert.match(images, /normalizeImage/);
  assert.match(board, /export class PuzzleBoard/);
  assert.match(board, /gameConfig\.pieces\.gap/);
  assert.match(board, /gridSize \* TILE_TEXTURE_SIZE/);
  assert.match(board, /sprite\.roundPixels = true/);
  assert.doesNotMatch(board, /const shadow = new Graphics/);
  assert.match(board, /relocateGroup/);
  assert.match(board, /recomputeConnections/);
  assert.match(board, /connectedNeighbors/);
  assert.match(board, /drawComponentOutline/);
  assert.match(board, /gameConfig\.pieces\.outlineWidth/);
  assert.doesNotMatch(board, /outline\.roundRect/);
  assert.match(board, /activeGroup\.forEach/);
  assert.match(board, /pointerdown/);
  assert.match(board, /pointermove/);
  assert.match(board, /tile\.slot === tile\.row \* gridSize \+ tile\.col/);
  assert.match(board, /coordinateFor/);
  assert.match(board, /coordinateDistance/);
  assert.match(board, /new Polygon\(tilePoints\)/);
  assert.match(board, /new Graphics\(\)\.poly\(tilePoints\)\.fill/);
  assert.match(board, /const hexImageSize = Math\.max\(gridWidth, gridHeight\)/);
  assert.match(board, /const octagonCut = tileWidth \* \(1 - Math\.SQRT1_2\)/);
  assert.match(board, /minimumSwapsToSolve/);
  assert.match(board, /onStart\(\)/);

  assert.match(scene, /export class PuzzleScene/);
  assert.match(scene, /new PuzzleBoard/);
  assert.match(scene, /new PuzzleHUD/);
  assert.match(scene, /new PuzzleControls/);
  assert.match(scene, /new TargetPreview/);
  assert.match(scene, /new CompletionModal/);
  assert.match(scene, /changeGridSize/);
  assert.match(scene, /changeTileShape/);
  assert.match(scene, /gameConfig\.scoring\.secondsPerStartingSet/);
  assert.match(scene, /this\.progress\.moves > this\.progress\.moveLimit/);
  assert.match(completion, /earnedStars === 3 \? "Excellent!" : earnedStars === 2 \? "Well done!" : "Puzzle completed!"/);
  assert.match(preview, /Reveal target image for a one-star penalty/);
  assert.match(preview, /<small aria-hidden="true">−★<\/small>/);
  assert.match(controls, /<legend>Piece shape<\/legend>/);
  assert.ok(controls.indexOf('class="shape-picker"') < controls.indexOf('class="grid-picker"'));
  assert.match(header, /soundManager\.toggleMuted\("music"\)/);
  assert.match(header, /Back to main menu/);
  assert.match(controls, />Upload image<input/);
  assert.doesNotMatch(scene + controls + preview + completion, /Picture complete!|Choose another image/);

  assert.match(soundManager, /export type SoundChannel = "music" \| "sfx"/);
  assert.match(soundManager, /playSound\(sound: string, loop = false, channel: SoundChannel = "sfx"\)/);
  assert.match(soundManager, /stopSound\(sound\?: string\)/);
  assert.match(soundManager, /toggleMuted\(channel: SoundChannel\)/);
  assert.match(themeManager, /export const themeManager/);
  assert.match(themeManager, /document\.documentElement\.dataset\.theme/);
  assert.match(sceneManager, /export class SceneManager/);
  assert.match(sceneManager, /export type SceneName = "gameIntro" \| "mainMenu" \| "puzzle"/);
  assert.match(sceneManager, /new GameIntroScene/);
  assert.match(sceneManager, /new MainMenuScene/);
  assert.match(sceneManager, /new PuzzleScene/);
  assert.match(sceneManager, /config: customLevelSceneConfig/);
  assert.match(sceneManager, /soundManager\.playSound\(this\.soundtrack, appConfig\.soundtrack\.loop, "music"\)/);
  assert.match(introScene, /Images provided by Pexels/);
  assert.match(introScene, /appConfig\.intro\.durationMs/);
  assert.match(mainMenuScene, />Play</);
  assert.match(mainMenuScene, />Custom Level</);
  assert.match(mainMenuScene, /accept="image\/\*"/);
  assert.match(mainMenuScene, /toggleMuted\("music"\)/);
  assert.match(mainMenuScene, /toggleMuted\("sfx"\)/);
  assert.match(scene, /initialImageFile/);
  assert.match(scene, /options\.onBack/);
  assert.match(styles, /:root\[data-theme="dark"\]/);
  assert.match(styles, /\.theme-toggle/);
  assert.match(hud, /export class PuzzleHUD/);
  assert.match(main, /new SceneManager\(root\)/);
  assert.ok(main.indexOf("themeManager.initialize()") < main.indexOf("new SceneManager(root)"));
  assert.doesNotMatch(main + scene + board + controls + header, /from "react"|react-dom|createRoot|useEffect|useState|useRef/);
});
